export const styles = {
  box: {
    width: { xs: "350px", md: "860px" },
    mb: "36px",
    display: "flex",
    flexDirection: "column",
  },
  boxXs: {
    width: "360px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderRadius: "12px",
    my: "32px",
    px: "20px",
    py: "12px",
    display: { xs: "flex", md: "none" },
    flexDirection: "column",
  },
  boxMd: {
    width: "820px",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: "12px",
    my: "32px",
    px: "44px",
    py: "22px",
    display: { xs: "none", md: "flex" },
    flexDirection: "column",
  },
  boxCompany: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  boxTeam: {
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    my: "12px",
    mx: "12px",
    gap: { xs: "12px", md: "32px" },
    alignItems: "flex-end",
    justifyContent: "flex-end",
    pr: "12px",
  },
  boxMember: {
    display: "flex",
    gap: "6px",
    borderRadius: "12px 0px 0px 12px",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    px: "8px",
    py: "2px",
  },
  text1: {
    fontSize: {
      xs: "1.5rem",
      md: "2rem",
    },
    color: "primary.main",
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  text2: {
    fontSize: {
      xs: "1.2rem",
      md: "1.5rem",
    },
    textAlign: "end",
    color: "secondary.main",
    opacity: "0.9",
  },
  text3: {
    fontSize: {
      xs: "1.2rem",
      md: "1.5rem",
    },
    color: "primary.main",
    opacity: "0.9",
  },
};
